# fly.toml app configuration file generated for fense-trivia-game on 2025-12-19T11:00:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fense-trivia-game'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  min_machines_running = 1
  max_machines_running = 1
  auto_stop_machines = false
  auto_start_machines = true
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
